/* ═══════════════════════════════════════════
   ZATHLETE — Données statiques
   Base alimentaire, citations, trophées, compléments
   ═══════════════════════════════════════════ */

/* ─── BASE ALIMENTAIRE ───
   p = protéines (g) · k = kcal · pour la portion indiquée
   u = libellé de la portion · q = quantité par défaut         */
const FOODS = {
  prot: {
    label:'Protéines', icon:'🥩',
    items:[
      {n:'Blanc de poulet',      u:'g', q:150, p:46, k:248},
      {n:'Cuisse de poulet',     u:'g', q:150, p:39, k:265},
      {n:'Poisson blanc',        u:'g', q:150, p:33, k:150},
      {n:'Thon en boîte',        u:'boîte', q:1, p:26, k:128},
      {n:'Thon frais',           u:'g', q:150, p:44, k:216},
      {n:'Saumon',               u:'g', q:150, p:31, k:312},
      {n:'Crevettes',            u:'g', q:150, p:36, k:149},
      {n:'Steak maigre',         u:'g', q:150, p:47, k:270},
      {n:'Viande hachée 5%',     u:'g', q:150, p:32, k:203},
      {n:'Agneau',               u:'g', q:150, p:38, k:390},
      {n:'Chèvre / mouton',      u:'g', q:150, p:39, k:330},
      {n:'Foie',                 u:'g', q:120, p:24, k:160},
      {n:'Œuf entier',           u:'œuf', q:2, p:13, k:143},
      {n:'Blanc d\u2019œuf',     u:'blanc', q:3, p:11, k:52},
      {n:'Yaourt nature',        u:'pot', q:1, p:6, k:75},
      {n:'Fromage blanc 0%',     u:'g', q:200, p:16, k:94},
      {n:'Skyr',                 u:'pot', q:1, p:17, k:96},
      {n:'Whey (dosette)',       u:'dose', q:1, p:24, k:120},
      {n:'Mozzarella',           u:'g', q:80, p:17, k:200},
      {n:'Fromage',              u:'g', q:40, p:10, k:160},
    ]
  },
  fec: {
    label:'Féculents', icon:'🍚',
    items:[
      {n:'Riz cuit',             u:'g', q:200, p:5, k:260},
      {n:'Pâtes cuites',         u:'g', q:200, p:10, k:300},
      {n:'Pommes de terre',      u:'g', q:200, p:4, k:174},
      {n:'Patate douce',         u:'g', q:200, p:3, k:172},
      {n:'Semoule / couscous',   u:'g', q:200, p:8, k:224},
      {n:'Quinoa cuit',          u:'g', q:180, p:8, k:216},
      {n:'Lentilles cuites',     u:'g', q:200, p:18, k:232},
      {n:'Soupe de lentilles',   u:'bol', q:1, p:14, k:210},
      {n:'Pois chiches',         u:'g', q:180, p:16, k:298},
      {n:'Haricots rouges',      u:'g', q:180, p:16, k:230},
      {n:'Pain complet',         u:'tranche', q:2, p:6, k:160},
      {n:'Pain blanc',           u:'tranche', q:2, p:5, k:170},
      {n:'Canjeero / injera',    u:'pièce', q:1, p:5, k:180},
      {n:'Chapati',              u:'pièce', q:1, p:5, k:210},
      {n:'Avoine',               u:'g', q:60, p:7, k:230},
      {n:'Banane plantain',      u:'g', q:150, p:2, k:180},
      {n:'Frites',               u:'g', q:150, p:5, k:465},
    ]
  },
  leg: {
    label:'Légumes', icon:'🥗',
    items:[
      {n:'Salade verte',         u:'bol', q:1, p:1, k:20},
      {n:'Tomate',               u:'pièce', q:2, p:2, k:36},
      {n:'Concombre',            u:'g', q:150, p:1, k:23},
      {n:'Courgette',            u:'g', q:200, p:2, k:34},
      {n:'Aubergine',            u:'g', q:200, p:2, k:50},
      {n:'Haricots verts',       u:'g', q:200, p:4, k:62},
      {n:'Épinards',             u:'g', q:150, p:4, k:35},
      {n:'Brocoli',              u:'g', q:200, p:6, k:68},
      {n:'Carotte',              u:'g', q:150, p:1, k:62},
      {n:'Oignon',               u:'pièce', q:1, p:1, k:44},
      {n:'Poivron',              u:'pièce', q:1, p:1, k:30},
      {n:'Chou',                 u:'g', q:200, p:3, k:50},
      {n:'Soupe de légumes',     u:'bol', q:1, p:3, k:90},
    ]
  },
  fru: {
    label:'Fruits', icon:'🍉',
    items:[
      {n:'Pastèque',             u:'g', q:300, p:2, k:90},
      {n:'Melon',                u:'g', q:250, p:2, k:85},
      {n:'Mangue',               u:'pièce', q:1, p:2, k:135},
      {n:'Papaye',               u:'g', q:250, p:1, k:108},
      {n:'Orange',               u:'pièce', q:1, p:1, k:62},
      {n:'Banane',               u:'pièce', q:1, p:1, k:105},
      {n:'Pomme',                u:'pièce', q:1, p:0, k:80},
      {n:'Ananas',               u:'g', q:200, p:1, k:100},
      {n:'Raisin',               u:'g', q:150, p:1, k:104},
      {n:'Fraises',              u:'g', q:200, p:1, k:64},
      {n:'Dattes',               u:'pièce', q:3, p:1, k:80},
    ]
  },
  gras: {
    label:'Matières grasses', icon:'🥑',
    items:[
      {n:'Huile d\u2019olive',   u:'c. à soupe', q:1, p:0, k:119},
      {n:'Avocat',               u:'demi', q:1, p:2, k:160},
      {n:'Noix',                 u:'poignée', q:1, p:4, k:185},
      {n:'Amandes',              u:'poignée', q:1, p:6, k:170},
      {n:'Cacahuètes',           u:'poignée', q:1, p:7, k:170},
      {n:'Beurre de cacahuète',  u:'c. à soupe', q:1, p:4, k:94},
      {n:'Graines de chia',      u:'c. à soupe', q:1, p:2, k:60},
      {n:'Graines de courge',    u:'poignée', q:1, p:7, k:160},
      {n:'Tahini',               u:'c. à soupe', q:1, p:3, k:89},
    ]
  },
  bois: {
    label:'Boissons', icon:'🥤',
    items:[
      {n:'Eau',                  u:'verre', q:1, p:0, k:0},
      {n:'Thé sans sucre',       u:'tasse', q:1, p:0, k:2},
      {n:'Café sans sucre',      u:'tasse', q:1, p:0, k:2},
      {n:'Lait',                 u:'verre', q:1, p:8, k:122},
      {n:'Jus d\u2019orange',    u:'verre', q:1, p:2, k:112},
      {n:'Jus de mangue',        u:'verre', q:1, p:1, k:130},
      {n:'Soda',                 u:'canette', q:1, p:0, k:139},
    ]
  }
};

/* Mots-clés pour estimer un aliment saisi librement */
const GUESS = [
  [/pizza/i,               {p:32, k:850}],
  [/shawarma|chawarma/i,   {p:34, k:620}],
  [/burger|hamburger/i,    {p:30, k:750}],
  [/tacos?/i,              {p:28, k:700}],
  [/kebab/i,               {p:32, k:650}],
  [/sandwich/i,            {p:20, k:450}],
  [/frite/i,               {p:5,  k:400}],
  [/couscous/i,            {p:22, k:520}],
  [/biryani|riz.*poulet/i, {p:35, k:640}],
  [/samo?sa|sambousa/i,    {p:8,  k:250}],
  [/poulet/i,              {p:40, k:260}],
  [/poisson|thon|saumon/i, {p:35, k:220}],
  [/viande|steak|b(oe|œ)uf/i,{p:40,k:300}],
  [/mouton|agneau|ch(e|è)vre/i,{p:38,k:380}],
  [/(oeuf|œuf)/i,          {p:13, k:145}],
  [/lentille/i,            {p:16, k:230}],
  [/riz/i,                 {p:5,  k:260}],
  [/p(a|â)tes|spaghetti/i, {p:10, k:300}],
  [/pain|chapati|canjeero/i,{p:6, k:180}],
  [/salade|l(e|é)gume/i,   {p:2,  k:60}],
  [/soupe/i,               {p:6,  k:140}],
  [/yaourt|fromage blanc/i,{p:8,  k:90}],
  [/fromage/i,             {p:10, k:160}],
  [/fruit|mangue|banane|past(e|è)que/i,{p:1,k:100}],
  [/g(a|â)teau|dessert|glace|chocolat/i,{p:5,k:400}],
  [/jus|soda/i,            {p:1,  k:120}],
];

/* ─── CITATIONS ─── */
const QUOTES = [
  ["La discipline, c'est choisir entre ce que tu veux maintenant et ce que tu veux le plus.","Anonyme"],
  ["Tu ne peux pas battre celui qui n'abandonne jamais.","Babe Ruth"],
  ["Le corps réalise ce que l'esprit croit.","Anonyme"],
  ["Ce n'est pas la charge qui te brise, c'est la façon dont tu la portes.","Lou Holtz"],
  ["Un jour ou jour un. À toi de choisir.","Anonyme"],
  ["La douleur que tu ressens aujourd'hui sera la force que tu sentiras demain.","Arnold Schwarzenegger"],
  ["La régularité bat l'intensité.","Anonyme"],
  ["Personne ne s'est jamais noyé dans sa sueur.","Ann Landers"],
  ["Le progrès, pas la perfection.","Anonyme"],
  ["Ce que tu fais aujourd'hui peut améliorer tous tes lendemains.","Ralph Marston"],
  ["Les excuses ne brûlent pas de calories.","Anonyme"],
  ["Sois plus fort que ta meilleure excuse.","Anonyme"],
  ["Une séance ratée ne casse rien. Dix séances ratées, si.","Anonyme"],
  ["Le succès, c'est la somme de petits efforts répétés jour après jour.","Robert Collier"],
  ["Tu es à une séance de ta bonne humeur.","Anonyme"],
  ["Ne compte pas les jours, fais que les jours comptent.","Mohamed Ali"],
  ["Le corps y arrive quand l'esprit décide.","Anonyme"],
  ["Ce qui est difficile aujourd'hui sera l'échauffement dans un an.","Anonyme"],
  ["La constance est plus rare que le talent.","Anonyme"],
  ["Fais-le fatigué. Fais-le quand même.","Anonyme"],
  ["On ne trouve jamais le temps, on le prend.","Anonyme"],
  ["Ton seul concurrent, c'est celui que tu étais hier.","Anonyme"],
  ["La motivation te lance, l'habitude te porte.","Jim Ryun"],
  ["Chaque expert a commencé débutant.","Helen Hayes"],
  ["Le repos fait partie de l'entraînement, pas de la paresse.","Anonyme"],
  ["Mange pour l'homme que tu veux devenir.","Anonyme"],
  ["La balance ne mesure ni ta force ni ta valeur.","Anonyme"],
  ["Un pas en arrière n'efface pas dix pas en avant.","Anonyme"],
  ["Le plus dur, c'est de mettre ses chaussures.","Anonyme"],
  ["Ce n'est pas un régime, c'est ta vie qui change.","Anonyme"],
  ["Fatigué ? Repose-toi. N'abandonne pas.","Banksy"],
  ["Ton futur toi te regarde en ce moment.","Anonyme"],
  ["Fort n'est pas une taille, c'est une décision.","Anonyme"],
  ["L'eau, le sommeil, les protéines. Le reste vient après.","Anonyme"],
  ["Le vrai adversaire, c'est la voix qui dit demain.","Anonyme"],
  ["Cinq minutes valent mieux que zéro.","Anonyme"],
  ["Les résultats arrivent après la période où tu voulais arrêter.","Anonyme"],
  ["On ne perd pas 15 kilos. On en perd un, quinze fois.","Anonyme"],
  ["Sois patient avec toi, mais ne sois pas indulgent.","Anonyme"],
  ["Le vendredi de repos t'appartient autant que le lundi de séance.","ZATHLETE"],
  ["Une semaine moyenne bien tenue vaut mieux qu'un jour parfait.","ZATHLETE"],
  ["Tu n'as pas besoin d'être motivé, tu as besoin d'être régulier.","ZATHLETE"],
  ["La faim passe. La fierté reste.","ZATHLETE"],
  ["Chaque série cochée est une brique du 80.","ZATHLETE"],
  ["Le premier jour était un point de départ. 80 est une décision.","ZATHLETE"],
];

/* ─── TROPHÉES ─── */
const TROPHIES = [
  {id:'first_w',  e:'⚖️', n:'Premier pas',          d:'Enregistrer ta première pesée'},
  {id:'w7',       e:'📅', n:'Une semaine de suivi',  d:'7 pesées enregistrées'},
  {id:'w30',      e:'🗓️', n:'Un mois de rigueur',    d:'30 pesées enregistrées'},
  {id:'kg1',      e:'🔻', n:'Le premier kilo',       d:'1 kg perdu depuis le début'},
  {id:'kg5',      e:'🏔️', n:'Cinq de moins',         d:'5 kg perdus'},
  {id:'kg10',     e:'💎', n:'Dix de moins',          d:'10 kg perdus'},
  {id:'phase2',   e:'2️⃣', n:'Phase 2 atteinte',      d:'Passer sous les 90 kg'},
  {id:'phase3',   e:'3️⃣', n:'Phase 3 atteinte',      d:'Passer sous les 85 kg'},
  {id:'goal',     e:'👑', n:'Objectif 80 kg',        d:'Atteindre les 80 kg'},
  {id:'s1',       e:'💪', n:'Première séance',       d:'Terminer une séance complète'},
  {id:'s10',      e:'🔥', n:'Dix séances',           d:'10 séances complètes'},
  {id:'s50',      e:'⚡', n:'Cinquante séances',     d:'50 séances complètes'},
  {id:'water',    e:'💧', n:'Bien hydraté',          d:'Atteindre ton objectif d\u2019eau'},
  {id:'water7',   e:'🌊', n:'Sept jours hydraté',    d:'Objectif d\u2019eau atteint 7 fois'},
  {id:'prot',     e:'🥩', n:'Objectif protéines',    d:'Atteindre ton objectif de protéines'},
  {id:'prot7',    e:'🍗', n:'Semaine protéinée',     d:'Objectif protéines atteint 7 fois'},
  {id:'meal20',   e:'📝', n:'Carnet bien tenu',      d:'20 repas enregistrés'},
  {id:'hebdo',    e:'📏', n:'Bilan du dimanche',     d:'Premier bilan complet'},
  {id:'hebdo4',   e:'📊', n:'Quatre bilans',         d:'4 bilans hebdomadaires'},
  {id:'taille5',  e:'📐', n:'Cinq centimètres',      d:'5 cm de tour de taille en moins'},
  {id:'sleep',    e:'😴', n:'Récupération',          d:'7 nuits de sommeil enregistrées'},
  {id:'lvl5',     e:'⭐', n:'Niveau 5',              d:'Atteindre le niveau 5'},
  {id:'lvl10',    e:'🌟', n:'Niveau 10',             d:'Atteindre le niveau 10'},
  {id:'beast',    e:'🦁', n:'Beast',                 d:'Athlete Score de 88 ou plus'},
];

/* ─── COMPLÉMENTS ─── */
const SUPPS = [
  {n:'Créatine monohydrate', s:'utile', e:'💊',
   d:'Le complément sportif le mieux documenté pour la force et la puissance. Ce n\u2019est pas un produit dopant.',
   dose:'3 à 5 g par jour, à n\u2019importe quel moment.',
   warn:'À valider avec un médecin en cas de problème rénal.'},
  {n:'Whey / protéine en poudre', s:'utile', e:'🥛',
   d:'Un moyen pratique d\u2019atteindre ton objectif de protéines quand les repas ne suffisent pas.',
   dose:'1 dose de 25 à 30 g si le total du jour est trop bas.',
   warn:'Ne remplace pas les repas complets.'},
  {n:'Vitamine D', s:'utile', e:'☀️',
   d:'Le déficit est courant. Rôle dans l\u2019os, l\u2019immunité et la fonction musculaire.',
   dose:'À déterminer après une prise de sang.',
   warn:'Ne pas surdoser sans contrôle médical.'},
  {n:'Oméga-3', s:'facultatif', e:'🐟',
   d:'Intéressant si tu manges peu de poisson gras.',
   dose:'1 à 2 g d\u2019EPA+DHA par jour.',
   warn:'Prudence si tu prends un anticoagulant.'},
  {n:'Magnésium', s:'facultatif', e:'🧂',
   d:'Impliqué dans la fonction musculaire et le sommeil. Utile si l\u2019alimentation est pauvre.',
   dose:'200 à 400 mg le soir.',
   warn:'Peut provoquer des troubles digestifs à forte dose.'},
  {n:'Spiruline', s:'facultatif', e:'🌿',
   d:'Complément nutritionnel. Ne remplace ni le poulet, ni le poisson, ni les œufs, ni les légumes.',
   dose:'3 à 5 g par jour.',
   warn:'Qualité très variable selon les marques.'},
  {n:'Graines de chia', s:'utile', e:'🌱',
   d:'Fibres, oméga-3 végétaux, satiété. Ce sont des aliments, pas des compléments.',
   dose:'1 à 2 cuillères à soupe.',
   warn:'Boire suffisamment avec.'},
  {n:'Brûleurs de graisse', s:'peu pertinent', e:'🚫',
   d:'Effet marginal et souvent surestimé. Beaucoup contiennent de fortes doses de stimulants.',
   dose:'—',
   warn:'À éviter avec une tension élevée. Parles-en à ton médecin.'},
];
