/* ═══════════════════════════════════════════
   ZATHLETE — Bibliothèque des mouvements
   Pictogrammes SVG + technique + muscles + repos
   ═══════════════════════════════════════════ */

/* Pictogrammes : bonhomme schématique, un par famille de mouvement.
   Tracé unique en currentColor pour s'adapter au thème.          */
const MOVE = {
  push_h:`<circle cx="26" cy="30" r="7"/><path d="M26 37v22"/><path d="M26 44h30M26 52h30"/><path d="M56 36v24M50 36v24"/><path d="M26 59l-8 14M26 59l8 14"/>`,
  push_v:`<circle cx="34" cy="52" r="7"/><path d="M34 59v20"/><path d="M34 60l-12-14M34 60l12-14"/><path d="M14 44h40"/><path d="M20 38v12M48 38v12"/><path d="M34 79l-9 13M34 79l9 13"/>`,
  fly:`<circle cx="34" cy="30" r="7"/><path d="M34 37v22"/><path d="M34 44H12M34 44h22"/><path d="M12 38v12M56 38v12"/><path d="M34 59l-8 14M34 59l8 14"/>`,
  raise:`<circle cx="34" cy="26" r="7"/><path d="M34 33v26"/><path d="M34 40H14M34 40h20"/><path d="M12 35v10M56 35v10"/><path d="M34 59l-8 16M34 59l8 16"/>`,
  dip:`<circle cx="34" cy="24" r="7"/><path d="M34 31v24"/><path d="M20 34v22M48 34v22"/><path d="M34 36H22M34 36h12"/><path d="M34 55l-6 12M34 55l10 10"/>`,
  pull_v:`<path d="M10 18h48"/><circle cx="34" cy="42" r="7"/><path d="M34 49v22"/><path d="M34 40L22 20M34 40l12-20"/><path d="M34 71l-8 14M34 71l8 14"/>`,
  pull_h:`<circle cx="26" cy="30" r="7"/><path d="M24 37l4 24"/><path d="M26 44h26"/><path d="M52 37v14"/><path d="M28 61l-8 14M28 61l10 12"/><path d="M16 44h8"/>`,
  curl:`<circle cx="34" cy="24" r="7"/><path d="M34 31v28"/><path d="M34 40l-12 8M34 40l12 8"/><path d="M22 48l4-10M46 48l-4-10"/><path d="M18 34h14M36 34h14"/><path d="M34 59l-8 16M34 59l8 16"/>`,
  squat:`<path d="M12 26h44"/><path d="M20 22v8M48 22v8"/><circle cx="34" cy="38" r="7"/><path d="M34 45v14"/><path d="M34 26H22M34 26h12"/><path d="M34 59l-12 10 4 16M34 59l12 10-4 16"/>`,
  lunge:`<circle cx="30" cy="24" r="7"/><path d="M30 31v22"/><path d="M18 40v14M44 40v14"/><path d="M30 53l-14 14v14M30 53l14 12v16"/><path d="M14 81h10"/>`,
  hinge:`<circle cx="20" cy="34" r="7"/><path d="M20 41l16 8"/><path d="M36 49h16"/><path d="M52 49l6 14"/><path d="M36 49l-4 22"/><path d="M20 41v-6"/>`,
  calf:`<circle cx="34" cy="22" r="7"/><path d="M34 29v26"/><path d="M34 55l-6 20M34 55l6 20"/><path d="M22 79h10M40 79h10"/><path d="M22 34h24"/>`,
  core:`<circle cx="18" cy="46" r="7"/><path d="M25 50h30"/><path d="M18 53v14M55 44v26"/><path d="M14 70h12M48 70h14"/>`,
  run:`<circle cx="40" cy="20" r="7"/><path d="M40 27l-6 20"/><path d="M40 32l14 8M40 32l-14 4"/><path d="M34 47l-10 18M34 47l14 12-4 16"/>`,
  carry:`<circle cx="34" cy="20" r="7"/><path d="M34 27v30"/><path d="M20 34v12M48 34v12"/><path d="M14 34h12M42 34h12"/><path d="M14 46h12M42 46h12"/><path d="M34 57l-7 22M34 57l7 22"/>`,
  sled:`<circle cx="24" cy="30" r="7"/><path d="M24 37l10 12"/><path d="M34 49h4"/><path d="M50 38v22M50 60h14"/><path d="M34 49L22 66M34 49l6 20"/><path d="M38 46h12"/>`,
  erg:`<circle cx="24" cy="34" r="7"/><path d="M24 41l6 14"/><path d="M30 48h22"/><path d="M52 42v12"/><path d="M30 55l16 6"/><path d="M14 68h44"/>`,
  jump:`<circle cx="34" cy="18" r="7"/><path d="M34 25v18"/><path d="M34 30l-14-6M34 30l14-6"/><path d="M34 43l-10 14M34 43l10 14"/><path d="M14 72h40"/>`,
  ball:`<circle cx="30" cy="34" r="7"/><circle cx="52" cy="18" r="9"/><path d="M30 41v16"/><path d="M30 40l14-14"/><path d="M30 57l-10 16M30 57l10 16"/>`,
  rope:`<circle cx="34" cy="20" r="7"/><path d="M34 27v22"/><path d="M34 34l-12 6M34 34l12 6"/><path d="M34 49l-7 18M34 49l7 18"/><path d="M14 40q20 34 40 0"/>`,
};

/* Fiches techniques.
   pat = pictogramme · mus = muscles · rest = repos conseillé (s)
   exec = points d'exécution · err = erreur fréquente             */
const EXINFO = {
  'Développé couché':{pat:'push_h',mus:'Pectoraux · Triceps · Épaules avant',rest:150,
    exec:['Omoplates serrées et plaquées au banc, pieds ancrés au sol.',
          'Descends la barre au niveau du bas des pectoraux, coudes à environ 45° du buste.',
          'Touche légèrement puis pousse en gardant les poignets alignés sur les avant-bras.'],
    err:'Coudes ouverts à 90° — ça met l\u2019épaule en tension inutile.'},
  'Développé militaire':{pat:'push_v',mus:'Épaules · Triceps · Gainage',rest:150,
    exec:['Debout, pieds largeur de bassin, abdos et fessiers contractés.',
          'Barre au niveau des clavicules, coudes légèrement devant.',
          'Pousse vers le haut en rentrant la tête quand la barre passe le front.'],
    err:'Cambrure lombaire pour compenser — serre le ventre et baisse la charge.'},
  'Écarté haltères incliné':{pat:'fly',mus:'Pectoraux (partie haute)',rest:90,
    exec:['Banc incliné à 30°, haltères au-dessus de la poitrine, coudes très légèrement fléchis.',
          'Ouvre lentement jusqu\u2019à sentir l\u2019étirement, sans descendre plus bas que le banc.',
          'Referme en imaginant que tu serres quelque chose entre tes coudes.'],
    err:'Plier les coudes en cours de route — ça transforme l\u2019écarté en développé.'},
  'Élévations latérales':{pat:'raise',mus:'Deltoïde latéral',rest:60,
    exec:['Buste très légèrement penché en avant, haltères le long du corps.',
          'Monte sur les côtés jusqu\u2019à l\u2019horizontale, pas plus haut.',
          'Redescends en trois secondes, sans relâcher d\u2019un coup.'],
    err:'Prendre trop lourd et s\u2019aider d\u2019un balancement du buste.'},
  'Dips triceps':{pat:'dip',mus:'Triceps · Pectoraux bas',rest:90,
    exec:['Buste le plus vertical possible pour cibler les triceps.',
          'Descends jusqu\u2019à ce que les coudes atteignent 90°.',
          'Remonte sans verrouiller violemment les coudes en haut.'],
    err:'Descendre trop bas et forcer sur l\u2019épaule.'},
  'Extension poulie haute':{pat:'curl',mus:'Triceps',rest:60,
    exec:['Coudes collés au corps et immobiles pendant tout le mouvement.',
          'Descends jusqu\u2019à l\u2019extension complète des bras.',
          'Marque une seconde de contraction en bas.'],
    err:'Bouger les coudes vers l\u2019avant — seuls les avant-bras travaillent.'},

  'Tirage vertical':{pat:'pull_v',mus:'Grand dorsal · Biceps',rest:120,
    exec:['Prise un peu plus large que les épaules, buste légèrement incliné en arrière.',
          'Tire la barre vers le haut de la poitrine en pensant à descendre les coudes.',
          'Contrôle la remontée, laisse les épaules s\u2019étirer en haut.'],
    err:'Tirer derrière la nuque — inutile et risqué pour l\u2019épaule.'},
  'Rowing barre':{pat:'pull_h',mus:'Dos épais · Trapèzes · Biceps',rest:150,
    exec:['Buste incliné à environ 45°, dos plat, genoux légèrement fléchis.',
          'Tire la barre vers le nombril en serrant les omoplates.',
          'Redescends en contrôlant, sans arrondir le bas du dos.'],
    err:'Se redresser pendant la série — c\u2019est le signe qu\u2019il faut alléger.'},
  'Tirage horizontal poulie':{pat:'pull_h',mus:'Milieu du dos · Biceps',rest:90,
    exec:['Dos droit, buste stable, jambes légèrement fléchies.',
          'Tire vers le nombril, coudes proches du corps.',
          'Serre les omoplates une seconde en fin de mouvement.'],
    err:'Balancer le buste d\u2019avant en arrière pour lancer la charge.'},
  'Face pull':{pat:'pull_h',mus:'Deltoïde arrière · Rotateurs',rest:60,
    exec:['Corde à hauteur de visage, prise pouces vers toi.',
          'Tire vers le front en écartant les mains.',
          'Termine coudes hauts, mains au niveau des oreilles.'],
    err:'Tirer trop lourd et vers la poitrine au lieu du visage.'},
  'Curl barre EZ':{pat:'curl',mus:'Biceps · Brachial',rest:75,
    exec:['Coudes collés au buste, épaules basses.',
          'Monte sans avancer les coudes, descends en contrôlant.',
          'Extension quasi complète en bas, sans relâcher totalement.'],
    err:'Utiliser le dos pour lancer la barre.'},
  'Curl marteau':{pat:'curl',mus:'Brachial · Avant-bras',rest:60,
    exec:['Prise neutre, paumes face à face.',
          'Monte un bras après l\u2019autre ou les deux ensemble.',
          'Redescends lentement sur trois secondes.'],
    err:'Tourner les poignets — ça enlève le travail du brachial.'},

  'Squat barre':{pat:'squat',mus:'Quadriceps · Fessiers · Gainage',rest:180,
    exec:['Barre posée sur les trapèzes, pieds largeur d\u2019épaules, pointes légèrement ouvertes.',
          'Descends en poussant les hanches en arrière, cuisses au moins parallèles au sol.',
          'Remonte en poussant le sol, genoux dans l\u2019axe des pieds.'],
    err:'Genoux qui rentrent vers l\u2019intérieur à la remontée.'},
  'Presse à cuisses':{pat:'squat',mus:'Quadriceps · Fessiers',rest:150,
    exec:['Pieds à mi-hauteur de la plateforme, largeur d\u2019épaules.',
          'Descends jusqu\u2019à 90° au genou sans décoller le bas du dos.',
          'Pousse sans verrouiller complètement les genoux en haut.'],
    err:'Bassin qui décolle en bas de la descente.'},
  'Fentes marchées':{pat:'lunge',mus:'Quadriceps · Fessiers · Équilibre',rest:120,
    exec:['Haltères le long du corps, buste droit.',
          'Grand pas en avant, genou arrière proche du sol.',
          'Pousse sur le talon avant pour enchaîner le pas suivant.'],
    err:'Pas trop courts — le genou avant dépasse largement la pointe du pied.'},
  'Leg curl allongé':{pat:'hinge',mus:'Ischio-jambiers',rest:90,
    exec:['Bassin plaqué au banc, chevilles sous le rouleau.',
          'Fléchis jusqu\u2019au maximum d\u2019amplitude.',
          'Marque une seconde en haut puis redescends lentement.'],
    err:'Décoller les hanches pour tricher sur les dernières répétitions.'},
  'Extension quadriceps':{pat:'hinge',mus:'Quadriceps',rest:75,
    exec:['Dos calé contre le dossier, mains sur les poignées.',
          'Tends les jambes jusqu\u2019à l\u2019extension complète.',
          'Bloque une seconde en haut, redescends en contrôlant.'],
    err:'Balancer les jambes en utilisant l\u2019élan.'},
  'Mollets debout':{pat:'calf',mus:'Mollets',rest:60,
    exec:['Pointes de pieds sur la marche, talons dans le vide.',
          'Descends les talons au maximum pour étirer.',
          'Monte le plus haut possible et tiens une seconde.'],
    err:'Faire des petits rebonds sans amplitude.'},

  'Course 1 km':{pat:'run',mus:'Cardio · Jambes',rest:120,
    exec:['Échauffement progressif sur les 200 premiers mètres.',
          'Cadence régulière, respiration par le nez si possible.',
          'Allure cible autour de 4\u201945"/km.'],
    err:'Partir trop vite et exploser à mi-parcours.'},
  'Sled push':{pat:'sled',mus:'Jambes · Gainage · Cardio',rest:120,
    exec:['Bras tendus, buste bas et incliné vers l\u2019avant.',
          'Pas courts et rapides, poussée continue avec les jambes.',
          'Ne t\u2019arrête pas au milieu du parcours.'],
    err:'Buste trop haut — tu pousses avec les bras au lieu des jambes.'},
  'Farmer carry':{pat:'carry',mus:'Grip · Trapèzes · Gainage',rest:120,
    exec:['Une charge dans chaque main, épaules basses et en arrière.',
          'Marche à pas réguliers, gainage actif, regard devant.',
          'Ne laisse pas les charges balancer sur les côtés.'],
    err:'Hausser les épaules et arrondir le haut du dos.'},
  'Rameur':{pat:'erg',mus:'Dos · Jambes · Cardio',rest:120,
    exec:['Séquence de poussée : jambes, puis tronc, puis bras.',
          'Retour en ordre inverse : bras, tronc, jambes.',
          'Cadence autour de 24 à 26 coups par minute.'],
    err:'Tirer avec les bras avant d\u2019avoir poussé sur les jambes.'},
  'Wall balls':{pat:'ball',mus:'Jambes · Épaules · Cardio',rest:90,
    exec:['Squat complet avec le ballon contre la poitrine.',
          'Utilise la remontée pour lancer le ballon vers la cible haute.',
          'Réceptionne et enchaîne directement le squat suivant.'],
    err:'Lancer uniquement avec les bras sans utiliser les jambes.'},
  'Burpees broad jump':{pat:'jump',mus:'Corps entier · Cardio',rest:90,
    exec:['Descends en position pompe, poitrine au sol.',
          'Remonte et enchaîne un saut en longueur vers l\u2019avant.',
          'Réception souple, genoux fléchis.'],
    err:'Réception jambes tendues — dur pour les genoux.'},

  'Course souple 3 km':{pat:'run',mus:'Cardio (zone 2)',rest:0,
    exec:['Allure à laquelle tu peux tenir une conversation.',
          'Respiration régulière, foulée relâchée.',
          'Si tu es essoufflé, ralentis : ce n\u2019est pas une séance dure.'],
    err:'Transformer la séance légère en séance intense.'},
  'Gainage planche':{pat:'core',mus:'Abdominaux profonds · Gainage',rest:60,
    exec:['Appui sur les avant-bras, coudes sous les épaules.',
          'Corps aligné de la tête aux talons, fessiers serrés.',
          'Respire normalement pendant tout le maintien.'],
    err:'Bassin qui remonte ou qui s\u2019affaisse.'},
  'Fentes marchées légères':{pat:'lunge',mus:'Jambes · Mobilité',rest:45,
    exec:['Au poids du corps, mouvement fluide.',
          'Cherche l\u2019amplitude plutôt que la vitesse.',
          'Buste droit tout du long.'],
    err:'Aller trop vite et perdre l\u2019équilibre.'},
  'Mountain climbers':{pat:'core',mus:'Gainage · Cardio',rest:45,
    exec:['Position pompe, mains sous les épaules.',
          'Ramène les genoux vers la poitrine en alternance.',
          'Garde les hanches basses et stables.'],
    err:'Fesses en l\u2019air — le gainage ne travaille plus.'},
  'Corde à sauter':{pat:'rope',mus:'Mollets · Cardio · Coordination',rest:30,
    exec:['Sauts bas, à peine décollés du sol.',
          'Rotation venant des poignets, pas des épaules.',
          'Réception sur l\u2019avant du pied.'],
    err:'Sauter trop haut et s\u2019épuiser en trente secondes.'},

  'Tractions pronation':{pat:'pull_v',mus:'Grand dorsal · Biceps',rest:150,
    exec:['Prise largeur d\u2019épaules ou légèrement plus, paumes vers l\u2019avant.',
          'Monte jusqu\u2019à passer le menton au-dessus de la barre.',
          'Descends en contrôlant jusqu\u2019aux bras presque tendus.'],
    err:'Faire des demi-répétitions avec du balancement.'},
  'Dips barres parallèles':{pat:'dip',mus:'Triceps · Pectoraux · Épaules',rest:120,
    exec:['Bras tendus au départ, épaules basses.',
          'Descends jusqu\u2019à 90° au coude, buste légèrement penché.',
          'Remonte en poussant fort sur les triceps.'],
    err:'Descendre trop bas et forcer l\u2019articulation de l\u2019épaule.'},
  'Pompes archer':{pat:'push_h',mus:'Pectoraux · Triceps (unilatéral)',rest:90,
    exec:['Mains très écartées, une jambe de chaque côté pour stabiliser.',
          'Descends d\u2019un côté en tendant le bras opposé.',
          'Alterne les côtés à chaque répétition.'],
    err:'Bassin qui tourne — garde les hanches face au sol.'},
  'L-sit':{pat:'core',mus:'Abdominaux · Fléchisseurs de hanche',rest:90,
    exec:['Mains au sol ou sur barres parallèles, épaules basses.',
          'Décolle le bassin, jambes tendues à l\u2019horizontale.',
          'Tiens le maximum, arrête dès que les jambes descendent.'],
    err:'Hausser les épaules vers les oreilles.'},
  'Pike push-up':{pat:'push_v',mus:'Épaules · Triceps',rest:90,
    exec:['Position en V inversé, fesses hautes.',
          'Descends le sommet du crâne vers le sol entre les mains.',
          'Pousse pour revenir bras tendus.'],
    err:'Plier les hanches en descendant au lieu de plier les coudes.'},
  'Hollow body hold':{pat:'core',mus:'Gainage antérieur',rest:60,
    exec:['Allongé sur le dos, bas du dos plaqué au sol.',
          'Décolle épaules et jambes, bras tendus derrière la tête.',
          'Si le dos décolle, remonte les jambes plus haut.'],
    err:'Creuser le bas du dos — le gainage n\u2019est plus protecteur.'},
};

/* Repli si un exercice n'a pas encore de fiche */
const EXINFO_DEFAULT = {pat:'core',mus:'Corps entier',rest:90,
  exec:['Garde une exécution contrôlée du début à la fin.',
        'Respire : expire à l\u2019effort, inspire au retour.',
        'Arrête la série si la technique se dégrade.'],
  err:'Aller trop vite au détriment de la technique.'};
function exInfo(n){return EXINFO[n]||EXINFO_DEFAULT}
