/* ═══════════════════════════════════════════
   ZATHLETE — Photos des mouvements
   Source : free-exercise-db (domaine public, Unlicense)
   Deux images par exercice : position de départ, position d'arrivée
   ═══════════════════════════════════════════ */
const EXPIC = {
  'Burpees broad jump'          : ['Front_Box_Jump_0.jpg', 'Front_Box_Jump_1.jpg'],
  'Corde à sauter'              : ['Rope_Jumping_0.jpg', 'Rope_Jumping_1.jpg'],
  'Course 1 km'                 : ['Running_Treadmill_0.jpg', 'Running_Treadmill_1.jpg'],
  'Course souple 3 km'          : ['Running_Treadmill_0.jpg', 'Running_Treadmill_1.jpg'],
  'Curl barre EZ'               : ['EZ-Bar_Curl_0.jpg', 'EZ-Bar_Curl_1.jpg'],
  'Curl marteau'                : ['Hammer_Curls_0.jpg', 'Hammer_Curls_1.jpg'],
  'Dips barres parallèles'      : ['Dips_-_Chest_Version_0.jpg', 'Dips_-_Chest_Version_1.jpg'],
  'Dips triceps'                : ['Dips_-_Triceps_Version_0.jpg', 'Dips_-_Triceps_Version_1.jpg'],
  'Développé couché'            : ['Barbell_Bench_Press_-_Medium_Grip_0.jpg', 'Barbell_Bench_Press_-_Medium_Grip_1.jpg'],
  'Développé militaire'         : ['Standing_Military_Press_0.jpg', 'Standing_Military_Press_1.jpg'],
  'Extension poulie haute'      : ['Triceps_Pushdown_0.jpg', 'Triceps_Pushdown_1.jpg'],
  'Extension quadriceps'        : ['Leg_Extensions_0.jpg', 'Leg_Extensions_1.jpg'],
  'Face pull'                   : ['Face_Pull_0.jpg', 'Face_Pull_1.jpg'],
  'Farmer carry'                : ['Farmers_Walk_0.jpg', 'Farmers_Walk_1.jpg'],
  'Fentes marchées'             : ['Dumbbell_Lunges_0.jpg', 'Dumbbell_Lunges_1.jpg'],
  'Fentes marchées légères'     : ['Bodyweight_Walking_Lunge_0.jpg', 'Bodyweight_Walking_Lunge_1.jpg'],
  'Gainage planche'             : ['Plank_0.jpg', 'Plank_1.jpg'],
  'Hollow body hold'            : ['Ab_Crunch_Machine_0.jpg', 'Ab_Crunch_Machine_1.jpg'],
  'L-sit'                       : ['Hanging_Leg_Raise_0.jpg', 'Hanging_Leg_Raise_1.jpg'],
  'Leg curl allongé'            : ['Lying_Leg_Curls_0.jpg', 'Lying_Leg_Curls_1.jpg'],
  'Mollets debout'              : ['Standing_Calf_Raises_0.jpg', 'Standing_Calf_Raises_1.jpg'],
  'Mountain climbers'           : ['Mountain_Climbers_0.jpg', 'Mountain_Climbers_1.jpg'],
  'Pike push-up'                : ['Hanging_Pike_0.jpg', 'Hanging_Pike_1.jpg'],
  'Pompes archer'               : ['Pushups_0.jpg', 'Pushups_1.jpg'],
  'Presse à cuisses'            : ['Leg_Press_0.jpg', 'Leg_Press_1.jpg'],
  'Rameur'                      : ['Seated_Cable_Rows_0.jpg', 'Seated_Cable_Rows_1.jpg'],
  'Rowing barre'                : ['Bent_Over_Barbell_Row_0.jpg', 'Bent_Over_Barbell_Row_1.jpg'],
  'Sled push'                   : ['Sled_Push_0.jpg', 'Sled_Push_1.jpg'],
  'Squat barre'                 : ['Barbell_Squat_0.jpg', 'Barbell_Squat_1.jpg'],
  'Tirage horizontal poulie'    : ['Seated_Cable_Rows_0.jpg', 'Seated_Cable_Rows_1.jpg'],
  'Tirage vertical'             : ['Wide-Grip_Lat_Pulldown_0.jpg', 'Wide-Grip_Lat_Pulldown_1.jpg'],
  'Tractions pronation'         : ['Pullups_0.jpg', 'Pullups_1.jpg'],
  'Wall balls'                  : ['Kettlebell_Thruster_0.jpg', 'Kettlebell_Thruster_1.jpg'],
  'Écarté haltères incliné'     : ['Incline_Dumbbell_Flyes_0.jpg', 'Incline_Dumbbell_Flyes_1.jpg'],
  'Élévations latérales'        : ['Side_Lateral_Raise_0.jpg', 'Side_Lateral_Raise_1.jpg'],
};


/* Photos des variantes (sans machine et mode voyage) */
const ALTPIC = {
  'Bear crawl'                          : ['Bear_Crawl_Sled_Drags_0.jpg', 'Bear_Crawl_Sled_Drags_1.jpg'],
  'Burpees'                             : ['Freehand_Jump_Squat_0.jpg', 'Freehand_Jump_Squat_1.jpg'],
  'Cercles de bras lents'               : ['Arm_Circles_0.jpg', 'Arm_Circles_1.jpg'],
  'Chaise murale'                       : ['Bodyweight_Squat_0.jpg', 'Bodyweight_Squat_1.jpg'],
  'Chaise murale lestée'                : ['Bodyweight_Squat_0.jpg', 'Bodyweight_Squat_1.jpg'],
  'Curl bidon d’eau'                    : ['Front_Dumbbell_Raise_0.jpg', 'Front_Dumbbell_Raise_1.jpg'],
  'Curl bidon prise neutre'             : ['Front_Dumbbell_Raise_0.jpg', 'Front_Dumbbell_Raise_1.jpg'],
  'Curl haltères'                       : ['Dumbbell_Bicep_Curl_0.jpg', 'Dumbbell_Bicep_Curl_1.jpg'],
  'Curl marteau haltères'               : ['Hammer_Curls_0.jpg', 'Hammer_Curls_1.jpg'],
  'Curl marteau élastique'              : ['Hammer_Curls_0.jpg', 'Hammer_Curls_1.jpg'],
  'Curl sac à dos chargé'               : ['Goblet_Squat_0.jpg', 'Goblet_Squat_1.jpg'],
  'Curl sac à dos prise neutre'         : ['Goblet_Squat_0.jpg', 'Goblet_Squat_1.jpg'],
  'Curl serviette auto-résistance'      : ['Standing_Towel_Triceps_Extension_0.jpg', 'Standing_Towel_Triceps_Extension_1.jpg'],
  'Curl élastique'                      : ['Dumbbell_Bicep_Curl_0.jpg', 'Dumbbell_Bicep_Curl_1.jpg'],
  'Dips entre deux chaises'             : ['Dips_-_Triceps_Version_0.jpg', 'Dips_-_Triceps_Version_1.jpg'],
  'Dips sur chaise'                     : ['Dips_-_Triceps_Version_0.jpg', 'Dips_-_Triceps_Version_1.jpg'],
  'Dips sur le bord du lit'             : ['Dips_-_Triceps_Version_0.jpg', 'Dips_-_Triceps_Version_1.jpg'],
  'Développé haltères au sol'           : ['Dumbbell_Bench_Press_0.jpg', 'Dumbbell_Bench_Press_1.jpg'],
  'Développé haltères debout'           : ['Dumbbell_Shoulder_Press_0.jpg', 'Dumbbell_Shoulder_Press_1.jpg'],
  'Développé élastique'                 : ['Band_Pull_Apart_0.jpg', 'Band_Pull_Apart_1.jpg'],
  'Développé élastique debout'          : ['Band_Pull_Apart_0.jpg', 'Band_Pull_Apart_1.jpg'],
  'Extension haltère nuque'             : ['Cable_Incline_Triceps_Extension_0.jpg', 'Cable_Incline_Triceps_Extension_1.jpg'],
  'Extension nuque haltère'             : ['Cable_Incline_Triceps_Extension_0.jpg', 'Cable_Incline_Triceps_Extension_1.jpg'],
  'Extension serviette isométrique'     : ['Cable_Incline_Triceps_Extension_0.jpg', 'Cable_Incline_Triceps_Extension_1.jpg'],
  'Extension élastique'                 : ['Cable_Incline_Triceps_Extension_0.jpg', 'Cable_Incline_Triceps_Extension_1.jpg'],
  'Face pull élastique'                 : ['Face_Pull_0.jpg', 'Face_Pull_1.jpg'],
  'Fentes arrière sac à dos'            : ['Goblet_Squat_0.jpg', 'Goblet_Squat_1.jpg'],
  'Fentes haltères'                     : ['Dumbbell_Lunges_0.jpg', 'Dumbbell_Lunges_1.jpg'],
  'Fentes lestées'                      : ['Dumbbell_Lunges_0.jpg', 'Dumbbell_Lunges_1.jpg'],
  'Fentes marchées'                     : ['Dumbbell_Lunges_0.jpg', 'Dumbbell_Lunges_1.jpg'],
  'Fentes marchées au poids du corps'   : ['Dumbbell_Lunges_0.jpg', 'Dumbbell_Lunges_1.jpg'],
  'Fentes marchées lestées'             : ['Dumbbell_Lunges_0.jpg', 'Dumbbell_Lunges_1.jpg'],
  'Fentes sautées alternées'            : ['Dumbbell_Lunges_0.jpg', 'Dumbbell_Lunges_1.jpg'],
  'Gainage latéral'                     : ['Side_Bridge_0.jpg', 'Side_Bridge_1.jpg'],
  'Gainage planche'                     : ['Plank_0.jpg', 'Plank_1.jpg'],
  'Glissés talons serviette'            : ['Lying_Leg_Curls_0.jpg', 'Lying_Leg_Curls_1.jpg'],
  'Goblet squat'                        : ['Goblet_Squat_0.jpg', 'Goblet_Squat_1.jpg'],
  'Goblet squat haltère'                : ['Goblet_Squat_0.jpg', 'Goblet_Squat_1.jpg'],
  'Hip thrust au sol'                   : ['Barbell_Hip_Thrust_0.jpg', 'Barbell_Hip_Thrust_1.jpg'],
  'Isométrie bras tendus'               : ['Front_Dumbbell_Raise_0.jpg', 'Front_Dumbbell_Raise_1.jpg'],
  'Kickback haltère'                    : ['Tricep_Dumbbell_Kickback_0.jpg', 'Tricep_Dumbbell_Kickback_1.jpg'],
  'Leg curl élastique'                  : ['Lying_Leg_Curls_0.jpg', 'Lying_Leg_Curls_1.jpg'],
  'Marche sur pointes'                  : ['Standing_Calf_Raises_0.jpg', 'Standing_Calf_Raises_1.jpg'],
  'Mollets haltères'                    : ['Standing_Calf_Raises_0.jpg', 'Standing_Calf_Raises_1.jpg'],
  'Mollets une jambe'                   : ['Standing_Calf_Raises_0.jpg', 'Standing_Calf_Raises_1.jpg'],
  'Mollets une jambe sur marche'        : ['Standing_Calf_Raises_0.jpg', 'Standing_Calf_Raises_1.jpg'],
  'Montées de genoux'                   : ['Mountain_Climbers_0.jpg', 'Mountain_Climbers_1.jpg'],
  'Nordic curl assisté'                 : ['Lying_Leg_Curls_0.jpg', 'Lying_Leg_Curls_1.jpg'],
  'Oiseau bouteilles d’eau'             : ['Front_Dumbbell_Raise_0.jpg', 'Front_Dumbbell_Raise_1.jpg'],
  'Oiseau haltères'                     : ['Reverse_Flyes_0.jpg', 'Reverse_Flyes_1.jpg'],
  'Pike push-up'                        : ['Hanging_Pike_0.jpg', 'Hanging_Pike_1.jpg'],
  'Pompes'                              : ['Pushups_0.jpg', 'Pushups_1.jpg'],
  'Pompes classiques'                   : ['Pushups_0.jpg', 'Pushups_1.jpg'],
  'Pompes diamant'                      : ['Pushups_0.jpg', 'Pushups_1.jpg'],
  'Pompes déclinées'                    : ['Pushups_0.jpg', 'Pushups_1.jpg'],
  'Pompes déclinées pieds surélevés'    : ['Pushups_0.jpg', 'Pushups_1.jpg'],
  'Pompes en appui mural'               : ['Pushups_0.jpg', 'Pushups_1.jpg'],
  'Pompes glissées serviette'           : ['Pushups_0.jpg', 'Pushups_1.jpg'],
  'Pompes lentes 4 secondes'            : ['Pushups_0.jpg', 'Pushups_1.jpg'],
  'Pompes lestées'                      : ['Pushups_0.jpg', 'Pushups_1.jpg'],
  'Pompes mains reculées'               : ['Pushups_0.jpg', 'Pushups_1.jpg'],
  'Pompes prise large'                  : ['Pushups_0.jpg', 'Pushups_1.jpg'],
  'Pont fessier une jambe'              : ['Butt_Lift_Bridge_0.jpg', 'Butt_Lift_Bridge_1.jpg'],
  'Port de bidons d’eau'                : ['Farmers_Walk_0.jpg', 'Farmers_Walk_1.jpg'],
  'Port de sacs de courses'             : ['Farmers_Walk_0.jpg', 'Farmers_Walk_1.jpg'],
  'Poussée de mur en appui'             : ['Sled_Push_0.jpg', 'Sled_Push_1.jpg'],
  'Push press bidon d’eau'              : ['Push_Press_0.jpg', 'Push_Press_1.jpg'],
  'Rotations externes élastique'        : ['External_Rotation_0.jpg', 'External_Rotation_1.jpg'],
  'Rowing haltère un bras'              : ['One-Arm_Dumbbell_Row_0.jpg', 'One-Arm_Dumbbell_Row_1.jpg'],
  'Rowing haltères buste penché'        : ['One-Arm_Dumbbell_Row_0.jpg', 'One-Arm_Dumbbell_Row_1.jpg'],
  'Rowing serviette isométrique'        : ['One-Arm_Dumbbell_Row_0.jpg', 'One-Arm_Dumbbell_Row_1.jpg'],
  'Rowing élastique'                    : ['One-Arm_Dumbbell_Row_0.jpg', 'One-Arm_Dumbbell_Row_1.jpg'],
  'Rowing élastique assis'              : ['One-Arm_Dumbbell_Row_0.jpg', 'One-Arm_Dumbbell_Row_1.jpg'],
  'Rowing élastique rapide'             : ['One-Arm_Dumbbell_Row_0.jpg', 'One-Arm_Dumbbell_Row_1.jpg'],
  'Sauts sur place'                     : ['Rope_Jumping_0.jpg', 'Rope_Jumping_1.jpg'],
  'Sauts à la corde'                    : ['Rope_Jumping_0.jpg', 'Rope_Jumping_1.jpg'],
  'Soulevé de terre jambes tendues'     : ['Smith_Machine_Stiff-Legged_Deadlift_0.jpg', 'Smith_Machine_Stiff-Legged_Deadlift_1.jpg'],
  'Sprint sur place genoux hauts'       : ['Mountain_Climbers_0.jpg', 'Mountain_Climbers_1.jpg'],
  'Squat + élévation bidon'             : ['Bodyweight_Squat_0.jpg', 'Bodyweight_Squat_1.jpg'],
  'Squat au poids du corps'             : ['Bodyweight_Squat_0.jpg', 'Bodyweight_Squat_1.jpg'],
  'Squat au poids du corps lent'        : ['Bodyweight_Squat_0.jpg', 'Bodyweight_Squat_1.jpg'],
  'Squat bulgare'                       : ['Barbell_Side_Split_Squat_0.jpg', 'Barbell_Side_Split_Squat_1.jpg'],
  'Squat bulgare au poids du corps'     : ['Barbell_Side_Split_Squat_0.jpg', 'Barbell_Side_Split_Squat_1.jpg'],
  'Squat pistolet assisté'              : ['Bodyweight_Squat_0.jpg', 'Bodyweight_Squat_1.jpg'],
  'Squat sauté'                         : ['Bodyweight_Squat_0.jpg', 'Bodyweight_Squat_1.jpg'],
  'Squat sauté bras au-dessus'          : ['Bodyweight_Squat_0.jpg', 'Bodyweight_Squat_1.jpg'],
  'Squat sauté bras tendus'             : ['Bodyweight_Squat_0.jpg', 'Bodyweight_Squat_1.jpg'],
  'Squat sauté enchaîné'                : ['Bodyweight_Squat_0.jpg', 'Bodyweight_Squat_1.jpg'],
  'Squat élastique'                     : ['Bodyweight_Squat_0.jpg', 'Bodyweight_Squat_1.jpg'],
  'Step-up sur banc'                    : ['Dumbbell_Step_Ups_0.jpg', 'Dumbbell_Step_Ups_1.jpg'],
  'Step-up sur chaise'                  : ['Dumbbell_Step_Ups_0.jpg', 'Dumbbell_Step_Ups_1.jpg'],
  'Superman au sol'                     : ['Superman_0.jpg', 'Superman_1.jpg'],
  'Superman avec tirage'                : ['Superman_0.jpg', 'Superman_1.jpg'],
  'Superman prolongé'                   : ['Superman_0.jpg', 'Superman_1.jpg'],
  'Suspension à la barre'               : ['Hanging_Bar_Good_Morning_0.jpg', 'Hanging_Bar_Good_Morning_1.jpg'],
  'Swing haltère'                       : ['One-Arm_Kettlebell_Swings_0.jpg', 'One-Arm_Kettlebell_Swings_1.jpg'],
  'Thruster haltères'                   : ['Kettlebell_Thruster_0.jpg', 'Kettlebell_Thruster_1.jpg'],
  'Thruster sac à dos'                  : ['Goblet_Squat_0.jpg', 'Goblet_Squat_1.jpg'],
  'Tirage serviette porte'              : ['Close-Grip_Front_Lat_Pulldown_0.jpg', 'Close-Grip_Front_Lat_Pulldown_1.jpg'],
  'Tirage élastique haut'               : ['Close-Grip_Front_Lat_Pulldown_0.jpg', 'Close-Grip_Front_Lat_Pulldown_1.jpg'],
  'Tractions australiennes'             : ['Inverted_Row_0.jpg', 'Inverted_Row_1.jpg'],
  'Tractions australiennes sous table'  : ['Inverted_Row_0.jpg', 'Inverted_Row_1.jpg'],
  'Tractions supination'                : ['Pullups_0.jpg', 'Pullups_1.jpg'],
  'Tractions à la barre'                : ['Pullups_0.jpg', 'Pullups_1.jpg'],
  'Valise portée en marchant'           : ['Farmers_Walk_0.jpg', 'Farmers_Walk_1.jpg'],
  'Version au poids du corps'           : ['Bodyweight_Squat_0.jpg', 'Bodyweight_Squat_1.jpg'],
  'Version haltères'                    : ['Decline_Dumbbell_Bench_Press_0.jpg', 'Decline_Dumbbell_Bench_Press_1.jpg'],
  'Version élastique'                   : ['Back_Flyes_-_With_Bands_0.jpg', 'Back_Flyes_-_With_Bands_1.jpg'],
  'W au sol'                            : ['Superman_0.jpg', 'Superman_1.jpg'],
  'ÃlÃ©vations bouteilles d’eau'       : ['Front_Dumbbell_Raise_0.jpg', 'Front_Dumbbell_Raise_1.jpg'],
  'Écarté au sol'                       : ['Dumbbell_Flyes_0.jpg', 'Dumbbell_Flyes_1.jpg'],
  'Écarté élastique'                    : ['Dumbbell_Flyes_0.jpg', 'Dumbbell_Flyes_1.jpg'],
  'Écartés serviette isométriques'      : ['Dumbbell_Flyes_0.jpg', 'Dumbbell_Flyes_1.jpg'],
  'Élévations frontales serviette'      : ['Side_Lateral_Raise_0.jpg', 'Side_Lateral_Raise_1.jpg'],
  'Élévations haltères'                 : ['Side_Lateral_Raise_0.jpg', 'Side_Lateral_Raise_1.jpg'],
  'Élévations élastique'                : ['Side_Lateral_Raise_0.jpg', 'Side_Lateral_Raise_1.jpg'],
};
function exPics(n){ return EXPIC[n] || ALTPIC[n] || null; }
